version: '3.8'

services:
  retropie:
    image: retropie
    build: .
    container_name: retropie

    #x-podman:
    #    in-pod: false

    deploy:
      replicas: 1

    # Enables rootless containers with proper user mapping for file permissions
    #userns_mode: "keep-id"
    # Loads environment variables from the .env file (for D-Bus)
    env_file:
      - .env
    
    # Run at higher priority (default: 1024)
    cpu_shares: 2048

    # Binds the container's network directly to the host for NetPlay/streaming
    network_mode: "host"

    # Needed?
    #privileged: true

    # Provides direct access to hardware for display and controllers
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/input:/dev/input"

    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}

    volumes:
      # Display & Hardware Mounts
      #- /tmp/.X11-unix:/tmp/.X11-unix:Z
      #- /dev/input:/dev/input
      #- /dev/dri:/dev/dri:Z
      #- ${XAUTHORITY}:/home/pie/.Xauthority:Z
      
      # Data Persistence Mounts
      - ./retropie-data/configs:/home/pie/.emulationstation:Z
      - ./retropie-data/configs-all:/opt/retropie/configs:Z
      - ./retropie-data/roms:/home/pie/RetroPie/roms:Z
      - ./retropie-data/bios:/home/pie/RetroPie/BIOS:Z
      - ./retropie-data/saves:/home/pie/RetroPie/saves:Z
      - ./retropie-data/states:/home/pie/RetroPie/states:Z

    restart: unless-stopped
