# v0.0.4
version: '3.8'

services:
  retropie:
    image: retropie
    build: .
    container_name: retropie
    
    cpu_shares: 2048
    network_mode: "host"
    privileged: true
    
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      
    volumes:
      # Display & Hardware Mounts
      - /tmp/.X11-unix:/tmp/.X11-unix:Z
      - /dev/input:/dev/input
      - /dev/dri:/dev/dri:Z
      - ${XAUTHORITY}:/home/pie/.Xauthority:Z
      
      # Data Persistence Mounts
      - ./retropie-data/configs:/home/pie/.emulationstation:Z
      - ./retropie-data/configs-all:/opt/retropie/configs:Z
      - ./retropie-data/roms:/home/pie/RetroPie/roms:Z
      - ./retropie-data/bios:/home/pie/RetroPie/BIOS:Z
      - ./retropie-data/saves:/home/pie/RetroPie/saves:Z
      - ./retropie-data/states:/home/pie/RetroPie/states:Z

    restart: unless-stopped
