version: '3.8'

services:
  retropie:
    image: retropie
    build: .
    container_name: retropie
    
    cpu_shares: 2048
    network_mode: "host"
    privileged: true
    
    environment:
      - DISPLAY=${DISPLAY}
      # Add XDG_RUNTIME_DIR
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      
    volumes:
      # Display & Hardware Mounts
      - /tmp/.X11-unix:/tmp/.X11-unix:Z
      - /dev/input:/dev/input
      # Mount GPU and X11 authentication cookie
      - /dev/dri:/dev/dri:Z
      - ${XAUTHORITY}:/home/pie/.Xauthority:Z
      
      # Mount the single host data directory to the single container data directory.
      - ./retropie-data:/data:Z

    restart: unless-stopped
