version: '3.8'

services:
  retropie:
    build:
      context: .
      args:
        UNAME: ${UNAME:?User name required}
        PUID: ${PUID:?User ID required}
        PGID: ${PGID:?Group ID required}
        IMAGE_NAME: ${IMAGE_NAME:?Image name required}
        CONTAINER_NAME: ${CONTAINER_NAME:?Container name required}
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    user: "${PUID}:${PGID}"
    restart: unless-stopped

    # Enables rootless containers with proper user mapping for file permissions
    # This currently is not working due to Podman bug.
    # Must use "podman-compose --pod-args '--userns keep-id'" instead
    # userns_mode: "keep-id"

    # Loads environment variables from the .env file
    env_file:
      - default.env
    
    # Run at higher priority (default: 1024)
    cpu_shares: 2048

    # Use host networking to give the container access to the host's network interfaces, including Bluetooth
    network_mode: host

    # Grant specific capabilities instead of full 'privileged' mode for better security
    cap_add:
      - NET_ADMIN  # Allows managing network interfaces
      - SYS_ADMIN  # Needed for a range of administrative tasks, often required by Bluetooth services

    # Provides direct access to hardware for display and controllers
    devices:
      - /dev/bus/usb
      - /dev/dri
      - /dev/input
      - /dev/snd
      - /dev/vga_arbiter

    environment:
      - DISPLAY=${DISPLAY}
      - TZ=${TZ}
      #- LIBGL_DRI3_ENABLE=1
      #- DRI_PRIME=1

    volumes:
      # Mount the D-Bus socket to allow communication with the host's Bluetooth service
      - /var/run/dbus:/var/run/dbus
      # Data Persistence Mounts
      - ${CONFIG_DIR}:/opt/retropie/configs
      - ${ROMS_DIR}:/home/${UNAME}/RetroPie/roms
      - ${BIOS_DIR}:/home/${UNAME}/RetroPie/BIOS
      # These will require special handling. ES needs to be configured to use these directories.
      - ${SAVES_DIR}:/home/${UNAME}/RetroPie/saves:Z
      - ${STATES_DIR}:/home/${UNAME}/RetroPie/states:Z
      # Share the X11 Socket
      #- /tmp/.X11-unix:/tmp/.X11-unix:ro


    # For debugging container. This line overrides the Dockerfile's ENTRYPOINT.
    # The container will start and do nothing indefinitely.
    #entrypoint: tail -f /dev/null
