version: '3.8'

services:
  retropie:
    image: retropie
    build: .
    container_name: retropie
    
    cpu_shares: 2048

    network_mode: "host"
    privileged: true
    
    environment:
      - DISPLAY=${DISPLAY}
      
    volumes:
      # Display & Hardware Mounts
      - /tmp/.X11-unix:/tmp/.X11-unix:Z
      - /dev/input:/dev/input
      - /dev/bus/usb:/dev/bus/usb
      - /run/udev/data:/run/udev/data
      
      # Data Persistence Mounts
      - ./retropie-data/configs:/home/pie/.emulationstation:Z
      - ./retropie-data/configs-all:/opt/retropie/configs:Z
      - ./retropie-data/roms:/home/pie/RetroPie/roms:Z
      - ./retropie-data/bios:/home/pie/RetroPie/BIOS:Z
      - ./retropie-data/saves:/home/pie/RetroPie/saves:Z
      - ./retropie-data/states:/home/pie/RetroPie/states:Z

    restart: unless-stopped
