version: '3.8'

services:
  retropie:
    build:
      context: .
      args:
        - UNAME: ${UNAME:?User Name required}
        - PUID: ${PUID:?User ID required}
        - PGID: ${PGID:?Group ID required}
        #- FOO: ${FOO:?FOO required}
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    user: "${PUID}:${PGID}"
    restart: unless-stopped

    # Enables rootless containers with proper user mapping for file permissions
    # This currently is not working due to Podman bug.
    # Must use "podman-compose --pod-args '--userns keep-id'" instead
    # userns_mode: "keep-id"

    # Loads environment variables from the .env file (for D-Bus)
    env_file:
      - .env
    
    # Run at higher priority (default: 1024)
    cpu_shares: 2048

    # Binds the container's network directly to the host for NetPlay/streaming
    network_mode: host

    # Provides direct access to hardware for display and controllers
    devices:
      - /dev/bus/usb
      - /dev/dri
      - /dev/input
      - /dev/snd

    environment:
      - DISPLAY=${DISPLAY}
      - TZ=${TZ}
      - PUID=11
      #- XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}

    volumes:
      # Data Persistence Mounts
      - ${CONFIG_DIR}:/opt/retropie/configs
      - ${ROMS_DIR}:/home/${UNAME}/RetroPie/roms
      - ${BIOS_DIR}:/home/${UNAME}/RetroPie/BIOS
      # These will require special handling. ES needs to be configured to use these directories.
      - ${SAVES_DIR}:/home/pie/RetroPie/saves:Z
      - ${STATES_DIR}:/home/pie/RetroPie/states:Z


    # For debugging. This line overrides the Dockerfile's ENTRYPOINT.
    # The container will start and do nothing indefinitely.
    #entrypoint: tail -f /dev/null
